service:
  name: product
frameworkVersion: '2'

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-west-1

functions:
  getProductList:
    handler: api/index.getProductList
    events:
      - http:
          path: product
          method: get
  getProductById:
    handler: api/index.getProductById
    events:
      - http:
          method: get
          path: /product/{id}
